import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/*
 * ------------------------------------------------------------
 * Obsidian plugin installation location
 * ------------------------------------------------------------
 */
const VAULT =
	"/storage/emulated/0/obsidian/Writing Vault/.obsidian/plugins/author-toolkit";

/*
 * ------------------------------------------------------------
 * Full project copy location
 *
 * The CONTENTS of the AuthorToolkit project are copied here.
 * The AuthorToolkit folder itself is NOT created inside it.
 * ------------------------------------------------------------
 */
const PROJECT_COPY =
	"/storage/emulated/0/Apps, Games & Plugins/ATK Plugin";

/*
 * ------------------------------------------------------------
 * Files/directories that should NOT be copied to ATK Plugin.
 *
 * .git:
 *   Git's internal repository data.
 *
 * node_modules:
 *   Installed dependencies. They are not part of the source
 *   project and can be recreated with npm install.
 *
 * my.zip:
 *   Temporary archive created for transferring the project.
 *
 * main.js:
 *   This IS normally part of the build output and should be
 *   copied, so it is intentionally NOT excluded.
 * ------------------------------------------------------------
 */
const EXCLUDED_DIRECTORIES = new Set([
	".git",
	"node_modules",
]);

const EXCLUDED_FILES = new Set([
	"my.zip",
]);

/**
 * Calculate a SHA-256 hash for a file.
 *
 * This is used to determine whether the actual contents of a
 * source file and destination file are different.
 */
function getFileHash(filePath) {
	const hash = crypto.createHash("sha256");

	hash.update(fs.readFileSync(filePath));

	return hash.digest("hex");
}

/**
 * Check whether two files have identical contents.
 */
function filesAreIdentical(sourcePath, destinationPath) {
	if (!fs.existsSync(destinationPath)) {
		return false;
	}

	const sourceStat = fs.statSync(sourcePath);
	const destinationStat = fs.statSync(destinationPath);

	/*
	 * Different sizes mean the files cannot be identical.
	 */
	if (sourceStat.size !== destinationStat.size) {
		return false;
	}

	return getFileHash(sourcePath) === getFileHash(destinationPath);
}

/**
 * Recursively synchronise the project contents.
 *
 * New files:
 *   copied.
 *
 * Changed files:
 *   copied.
 *
 * Unchanged files:
 *   skipped.
 *
 * Deleted source files:
 *   NOT deleted from the destination.
 *
 * This makes the operation safe and one-way.
 */
function syncProjectFiles(sourceDirectory, destinationDirectory) {
	fs.mkdirSync(destinationDirectory, {
		recursive: true,
	});

	const entries = fs.readdirSync(sourceDirectory, {
		withFileTypes: true,
	});

	let copiedCount = 0;
	let skippedCount = 0;

	for (const entry of entries) {
		const sourcePath = path.join(
			sourceDirectory,
			entry.name
		);

		const destinationPath = path.join(
			destinationDirectory,
			entry.name
		);

		/*
		 * Skip excluded directories.
		 */
		if (
			entry.isDirectory() &&
			EXCLUDED_DIRECTORIES.has(entry.name)
		) {
			continue;
		}

		/*
		 * Skip excluded files.
		 */
		if (
			entry.isFile() &&
			EXCLUDED_FILES.has(entry.name)
		) {
			continue;
		}

		/*
		 * Recursively process directories.
		 */
		if (entry.isDirectory()) {
			const result = syncProjectFiles(
				sourcePath,
				destinationPath
			);

			copiedCount += result.copiedCount;
			skippedCount += result.skippedCount;

			continue;
		}

		/*
		 * Only copy regular files.
		 */
		if (!entry.isFile()) {
			continue;
		}

		/*
		 * If the destination already contains the exact same
		 * contents, don't copy it again.
		 */
		if (
			filesAreIdentical(
				sourcePath,
				destinationPath
			)
		) {
			skippedCount++;
			continue;
		}

		/*
		 * Make sure the destination directory exists.
		 */
		fs.mkdirSync(
			path.dirname(destinationPath),
			{
				recursive: true,
			}
		);

		/*
		 * Copy the new/changed file.
		 */
		fs.copyFileSync(
			sourcePath,
			destinationPath
		);

		copiedCount++;

		console.log(
			`  ↳ Copied: ${path.relative(
				process.cwd(),
				sourcePath
			)}`
		);
	}

	return {
		copiedCount,
		skippedCount,
	};
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();

	/*
	 * ------------------------------------------------------------
	 * 1. Copy the BUILD OUTPUT to the native Obsidian plugin
	 *    folder.
	 * ------------------------------------------------------------
	 */

	fs.mkdirSync(VAULT, {
		recursive: true,
	});

	fs.copyFileSync(
		"main.js",
		path.join(VAULT, "main.js")
	);

	fs.copyFileSync(
		"manifest.json",
		path.join(VAULT, "manifest.json")
	);

	if (fs.existsSync("styles.css")) {
		fs.copyFileSync(
			"styles.css",
			path.join(VAULT, "styles.css")
		);
	}

	console.log("✓ Plugin copied to vault.");

	/*
	 * ------------------------------------------------------------
	 * 2. Synchronise the COMPLETE PROJECT to ATK Plugin.
	 * ------------------------------------------------------------
	 *
	 * Source:
	 *
	 *   Your AuthorToolkit project folder
	 *
	 * Destination:
	 *
	 *   /storage/emulated/0/Apps, Games & Plugins/ATK Plugin
	 *
	 * Only new or changed files are copied.
	 */

	console.log("");
	console.log("Syncing project files...");

	const syncResult = syncProjectFiles(
		process.cwd(),
		PROJECT_COPY
	);

	console.log(
		`✓ Project sync complete: ${syncResult.copiedCount} copied, ${syncResult.skippedCount} unchanged.`
	);

	console.log(
		`✓ Project copy: ${PROJECT_COPY}`
	);

	process.exit(0);
} else {
	await context.watch();
}